use std::{
    fs,
    path::{Path, PathBuf},
};

use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Schema {
    version: u32,
    tables: Vec<Table>,
}

#[derive(Debug, Deserialize)]
struct Table {
    name: String,
    columns: Vec<Column>,
}

#[derive(Debug, Deserialize)]
struct Column {
    name: String,
    #[serde(rename = "type")]
    kind: String,
    #[serde(default)]
    required: bool,
    #[serde(default)]
    default: Option<serde_json::Value>,
}

pub struct CodegenOutcome {
    pub output: PathBuf,
    pub changed: bool,
}

pub fn generate(project: &Path, check: bool) -> Result<CodegenOutcome, String> {
    let manifest_source = fs::read_to_string(project.join("rustframe.json"))
        .map_err(|error| format!("failed to read rustframe.json: {error}"))?;
    let manifest: serde_json::Value = serde_json::from_str(&manifest_source)
        .map_err(|error| format!("failed to parse rustframe.json: {error}"))?;
    let schema_relative = manifest
        .pointer("/database/schema")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("data/schema.json");
    let output_relative = manifest
        .pointer("/frontend/generatedTypes")
        .and_then(serde_json::Value::as_str)
        .unwrap_or("src/rustframe.generated.ts");
    let schema_path = project.join(schema_relative);
    let output = project.join(output_relative);
    let source = fs::read_to_string(&schema_path)
        .map_err(|error| format!("failed to read '{}': {error}", schema_path.display()))?;
    let schema: Schema = serde_json::from_str(&source)
        .map_err(|error| format!("failed to parse '{}': {error}", schema_path.display()))?;
    let generated = if output.extension().and_then(|value| value.to_str()) == Some("js") {
        render_javascript(&schema)
    } else {
        render_typescript(&schema)
    };
    let current = fs::read_to_string(&output).ok();
    let current_normalized = current.as_deref().map(|value| value.replace("\r\n", "\n"));
    let changed = current_normalized.as_deref() != Some(generated.as_str());

    if check && changed {
        return Err(format!(
            "generated database types are stale: run `rustframe codegen` to update {}",
            output.display()
        ));
    }
    if !check && changed {
        if let Some(parent) = output.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create '{}': {error}", parent.display()))?;
        }
        fs::write(&output, generated)
            .map_err(|error| format!("failed to write '{}': {error}", output.display()))?;
    }

    Ok(CodegenOutcome { output, changed })
}

fn render_typescript(schema: &Schema) -> String {
    let mut output = format!(
        "// Generated by rustframe codegen from database schema v{}. Do not edit.\n\nimport type {{ RustFrameClient }} from \"rustframe-api\";\n\n",
        schema.version
    );
    for table in &schema.tables {
        let base = type_name(&table.name);
        output.push_str(&format!("export interface {base}Record {{\n"));
        output.push_str("  id: number;\n  createdAt: string;\n  updatedAt: string;\n");
        for column in &table.columns {
            output.push_str(&format!(
                "  {}{}: {};\n",
                safe_property(&column.name),
                if column.required { "" } else { "?" },
                ts_type(&column.kind)
            ));
        }
        output.push_str("}\n\n");

        output.push_str(&format!("export interface {base}Insert {{\n"));
        for column in &table.columns {
            let optional = !column.required || column.default.is_some();
            output.push_str(&format!(
                "  {}{}: {};\n",
                safe_property(&column.name),
                if optional { "?" } else { "" },
                ts_type(&column.kind)
            ));
        }
        output.push_str("}\n\n");
        output.push_str(&format!(
            "export type {base}Update = Partial<{base}Insert>;\n\n"
        ));
    }
    output.push_str("export interface RustFrameTableMap {\n");
    for table in &schema.tables {
        let base = type_name(&table.name);
        output.push_str(&format!(
            "  {}: {{ record: {base}Record; insert: {base}Insert; update: {base}Update }};\n",
            safe_property(&table.name)
        ));
    }
    output.push_str("}\n\nexport type AppRustFrameClient = RustFrameClient<RustFrameTableMap>;\n");
    output
}

fn render_javascript(schema: &Schema) -> String {
    let mut output = format!(
        "// Generated by rustframe codegen from database schema v{}. Do not edit.\n// This file intentionally contains only JSDoc so vanilla JavaScript projects need no TypeScript compiler.\n\n",
        schema.version
    );
    for table in &schema.tables {
        let base = type_name(&table.name);
        output.push_str("/**\n * @typedef {Object} ");
        output.push_str(&format!("{base}Record\n * @property {{number}} id\n * @property {{string}} createdAt\n * @property {{string}} updatedAt\n"));
        for column in &table.columns {
            output.push_str(&format!(
                " * @property {{{}}} {}\n",
                js_type(&column.kind, !column.required),
                column.name
            ));
        }
        output.push_str(" */\n\n");
    }
    output.push_str("export {};\n");
    output
}

fn type_name(table: &str) -> String {
    let mut value = table
        .split(|character: char| !character.is_ascii_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| first.to_ascii_uppercase().to_string() + chars.as_str())
                .unwrap_or_default()
        })
        .collect::<String>();
    if value.ends_with('s') && value.len() > 1 {
        value.pop();
    }
    if value.is_empty() {
        "Table".into()
    } else {
        value
    }
}

fn safe_property(value: &str) -> String {
    if value.chars().enumerate().all(|(index, character)| {
        character.is_ascii_alphanumeric() || character == '_' || (index > 0 && character == '$')
    }) {
        value.to_string()
    } else {
        serde_json::to_string(value).expect("string serialization")
    }
}

fn ts_type(kind: &str) -> &'static str {
    match kind {
        "integer" | "real" => "number",
        "boolean" => "boolean",
        "json" => "unknown",
        _ => "string",
    }
}

fn js_type(kind: &str, optional: bool) -> String {
    let base = match kind {
        "integer" | "real" => "number",
        "boolean" => "boolean",
        "json" => "*",
        _ => "string",
    };
    if optional {
        format!("{base}|undefined")
    } else {
        base.into()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_type_checks_ignore_platform_line_endings() {
        let project = tempfile::tempdir().unwrap();
        fs::create_dir_all(project.path().join("data")).unwrap();
        fs::write(
            project.path().join("rustframe.json"),
            r#"{"database":{"schema":"data/schema.json"},"frontend":{"generatedTypes":"src/rustframe.generated.ts"}}"#,
        )
        .unwrap();
        fs::write(
            project.path().join("data/schema.json"),
            r#"{"version":1,"tables":[]}"#,
        )
        .unwrap();

        let generated = render_typescript(&Schema {
            version: 1,
            tables: Vec::new(),
        });
        fs::create_dir_all(project.path().join("src")).unwrap();
        fs::write(
            project.path().join("src/rustframe.generated.ts"),
            generated.replace('\n', "\r\n"),
        )
        .unwrap();

        let outcome = generate(project.path(), true).unwrap();
        assert!(!outcome.changed);
    }

    #[test]
    fn generated_types_are_stable_and_separate_mutation_shapes() {
        let schema = Schema {
            version: 1,
            tables: vec![Table {
                name: "work_items".into(),
                columns: vec![Column {
                    name: "title".into(),
                    kind: "text".into(),
                    required: true,
                    default: None,
                }],
            }],
        };
        let output = render_typescript(&schema);
        assert!(output.contains("interface WorkItemRecord"));
        assert!(output.contains("interface WorkItemInsert"));
        assert!(output.contains("type WorkItemUpdate = Partial<WorkItemInsert>"));
    }

    #[test]
    fn website_codegen_fixture_matches_the_cli() {
        let schema: Schema =
            serde_json::from_str(include_str!("../../../site/examples/schema.json")).unwrap();
        let expected = include_str!("../../../site/examples/rustframe.generated.ts");

        assert_eq!(render_typescript(&schema), expected.replace("\r\n", "\n"));
    }
}
