import fs from "node:fs";
import path from "node:path";
import ts from "../packages/rustframe-api/node_modules/typescript/lib/typescript.js";

const repoRoot = path.resolve(import.meta.dirname, "..");
const check = process.argv.includes("--check");

function writeGenerated(relativePath, contents) {
  const output = path.join(repoRoot, relativePath);
  const current = fs.existsSync(output) ? fs.readFileSync(output, "utf8") : null;
  if (check && current !== contents) {
    console.error(`${relativePath} is stale; run node scripts/generate_reference_docs.mjs`);
    process.exitCode = 1;
    return;
  }
  if (!check && current !== contents) fs.writeFileSync(output, contents);
}

function hasExport(node) {
  return node.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword);
}

function declarationName(node) {
  if (node.name?.text) return node.name.text;
  if (ts.isVariableStatement(node)) {
    return node.declarationList.declarations.map((declaration) => declaration.name.getText()).join(", ");
  }
  return null;
}

const apiPath = path.join(repoRoot, "packages/rustframe-api/src/index.ts");
const apiSourceText = fs.readFileSync(apiPath, "utf8");
const apiSource = ts.createSourceFile(apiPath, apiSourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
const declarations = apiSource.statements
  .filter((node) => hasExport(node))
  .map((node) => ({ name: declarationName(node), kind: ts.SyntaxKind[node.kind], source: node.getText(apiSource) }))
  .filter((entry) => entry.name);

let apiMarkdown = `# Frontend API reference\n\n> Generated from \`packages/rustframe-api/src/index.ts\`. Do not edit this file directly. Run \`node scripts/generate_reference_docs.mjs\` after changing the public frontend types.\n\nThe frontend package is currently documented at release candidate \`0.1.0-rc.1\`. The initial npm publication remains a public registry gate; this reference describes the source and tested package contract.\n\n## Index\n\n`;
apiMarkdown += declarations.map((entry) => `- [${entry.name}](#${entry.name.toLowerCase().replace(/[^a-z0-9]+/g, "-")})`).join("\n");
apiMarkdown += "\n\n";
for (const declaration of declarations) {
  apiMarkdown += `## ${declaration.name}\n\nSource declaration kind: \`${declaration.kind}\`.\n\n\`\`\`typescript\n${declaration.source}\n\`\`\`\n\n`;
}
writeGenerated("docs/api-reference.md", apiMarkdown);

const manifestSchema = JSON.parse(fs.readFileSync(path.join(repoRoot, "schemas/v1/rustframe.schema.json"), "utf8"));
const manifestRows = [];

function describeContract(schema) {
  const parts = [];
  if (schema.const !== undefined) parts.push(`constant \`${JSON.stringify(schema.const)}\``);
  else if (schema.enum) parts.push(schema.enum.map((value) => `\`${value}\``).join(" or "));
  else if (schema.$ref) parts.push(`\`${schema.$ref}\``);
  else if (schema.type === "array") parts.push("array");
  else if (schema.type) parts.push(schema.type);
  if (schema.pattern) parts.push(`pattern \`${schema.pattern.replaceAll("|", "\\|")}\``);
  if (schema.minimum !== undefined) parts.push(`min ${schema.minimum}`);
  if (schema.maximum !== undefined) parts.push(`max ${schema.maximum}`);
  if (schema.minLength !== undefined) parts.push(`min length ${schema.minLength}`);
  if (schema.minItems !== undefined) parts.push(`min items ${schema.minItems}`);
  if (schema.uniqueItems) parts.push("unique items");
  if (schema.default !== undefined) parts.push(`default \`${JSON.stringify(schema.default)}\``);
  return parts.join("; ") || "object";
}

function collectProperties(schema, prefix = "", required = []) {
  for (const [name, property] of Object.entries(schema.properties || {})) {
    const propertyPath = prefix ? `${prefix}.${name}` : name;
    manifestRows.push({ path: propertyPath, required: required.includes(name), contract: describeContract(property) });
    if (property.type === "object") collectProperties(property, propertyPath, property.required || []);
    if (property.type === "array" && property.items?.type === "object") {
      collectProperties(property.items, `${propertyPath}[]`, property.items.required || []);
    }
  }
}
collectProperties(manifestSchema, "", manifestSchema.required || []);

let manifestMarkdown = `# Manifest reference\n\n> Generated from \`schemas/v1/rustframe.schema.json\`. Do not edit this file directly. The immutable public schema is [available on GitHub Pages](${manifestSchema.$id}).\n\nManifest schema v1 rejects unknown properties. Paths, capabilities, and release metadata remain subject to the semantic validation performed by \`rustframe validate\` in addition to the JSON Schema constraints below.\n\n## Fields\n\n| Path | Required | Schema contract |\n| --- | --- | --- |\n`;
manifestMarkdown += manifestRows.map((row) => `| \`${row.path}\` | ${row.required ? "yes" : "no"} | ${row.contract} |`).join("\n");
manifestMarkdown += `\n\n## Validate a manifest\n\n\`\`\`bash\nrustframe validate\n\`\`\`\n\nUse [Runtime and capabilities](./runtime-and-capabilities.md) for the authorization model, [Threat model](./threat-model.md) for security boundaries, and [Migrations and versioning](./migrations-and-versioning.md) before changing schema versions.\n`;
writeGenerated("docs/manifest-reference.md", manifestMarkdown);

if (!process.exitCode) {
  console.log(`Reference docs ${check ? "verified" : "generated"}: ${declarations.length} API declarations and ${manifestRows.length} manifest fields.`);
}
